markdown: rdiscount
pygments: true
auto: true
rdiscount:
  extensions: [smart]

url: http://designiseasy.com
description: A fantastic blog that is fantastic.
twitter: designiseasy
permalinks: pretty
exclude: ['sass', 'atom.xml', 'readme.markdown', 'LICENSE', 'CNAME']
