markdown: rdiscount
pygments: true
rdiscount:
  extensions: [smart]

url: http://designiseasy.com
name: Design is Easy
description: A fantastic blog that is fantastic.
twitter: designiseasy
permalink: /:categories/:title.html
exclude: ['sass', 'Gemfile', 'Gemfile.lock', 'deploy', 'site_deploy.sh', 'atom.xml', 'readme.markdown', 'LICENSE', 'CNAME']

asset_bundler:
  compress:
    js: 'closure'
    css: false
  base_path: /static/built/
  server_url:
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"


prose:
  rooturl: "_posts"
  metadata:
    "_posts/work": |
      title:    "Title of your article"
      client: "Client Here"
      name: "Project Name Here"
      work-desc: "Abstract"
      category: work
      preview-image: name-of-image.jpg
    "_posts/projects": |
      name: "Project Name"
      img:  "Project Thumbnail"
